export const MOVIES = [
    {
        id: 1,
        title: "Avatar:",
        subtitle: "Fire and Ash",
        rating: "8.7",
        duration: "3h 17min",
        genres: ["Sci-Fi", "Adventure"],
        description: "Journey beyond the forests of Pandora to the treacherous Volcanic Plains. Experience the next epic chapter in the battle for survival.",
        image: "https://miro.medium.com/v2/resize:fit:2000/1*VeTHBNBbAUZh0LDs7DpT1g.jpeg",
    },
    {
        id: 2,
        title: "Dune:",
        subtitle: "Part Two",
        rating: "8.9",
        duration: "2h 46min",
        genres: ["Sci-Fi", "Drama"],
        description: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
        image: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2024/02/dune_-part-two-poster-2024.jpg?w=1600&h=900&fit=crop",
    },
    {
        id: 3,
        title: "Avengers:",
        subtitle: "Endgame",
        rating: "8.4",
        duration: "3h 02min",
        genres: ["Action", "Sci-Fi"],
        description: "The universe is in ruins. The remaining Avengers assemble once more in order to restore balance to the universe.",
        image: "https://cdn.marvel.com/content/2x/avengersendgame_lob_mas_mob_01.jpg",
    },
    {
        id: 4,
        title: "The Bad Guys 2",
        subtitle: "The Heist Continues",
        rating: "8.2",
        duration: "1h 45min",
        genres: ["Animation", "Comedy"],
        description: "The reformed crew of outlaws struggles to stay on the good side when an old life of crime comes knocking.",
        image: "https://image.tmdb.org/t/p/original/8FWLJHuWB72UXBmiMtxwTvQVumN.jpg",
    },
    {
        id: 5,
        title: "Godzilla x Kong:",
        subtitle: "The New Empire",
        rating: "6.7",
        duration: "1h 55min",
        genres: ["Action", "Adventure"],
        description: "Two ancient titans face off in an epic battle as humans unravel their intertwined origins.",
        image: "https://www.slashfilm.com/img/gallery/does-godzilla-x-kong-the-new-empire-have-a-credits-scene-a-spoiler-free-guide/l-intro-1711484152.jpg",
    },
    {
        id: 6,
        title: "Spider-Man:",
        subtitle: "Beyond the Spider-Verse",
        rating: "9.1",
        duration: "2h 20min",
        genres: ["Animation", "Action"],
        description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.",
        image: "https://i.pathehome.com/product/global/phf-cfw4oa1vty/4e7497-spidermanacrossthespiderverse_b_fr.jpg?w=3840&auto=format&crop=top%2Cleft&fit=crop&q=45",
    },
    {
        id: 7,
        title: "Oppenheimer",
        subtitle: "The World Forever Changes",
        rating: "8.8",
        duration: "3h 00min",
        genres: ["Drama", "History"],
        description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
        image: "https://www.thebanner.org/sites/default/files/styles/article_detail_header/public/2023-08/MM-1207%20Oppenheimer.jpg?itok=0U-jOPJC",
    },
    {
        id: 8,
        title: "The Batman",
        subtitle: "Unmask The Truth",
        rating: "7.8",
        duration: "2h 56min",
        genres: ["Crime", "Action"],
        description: "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
        image: "https://static0.cbrimages.com/wordpress/wp-content/uploads/2022/02/The-Batman-Bats.jpg?q=50&fit=crop&w=825&dpr=1.5",
    },
    {
        id: 9,
        title: "Interstellar",
        subtitle: "Experience it in IMAX",
        rating: "8.7",
        duration: "2h 49min",
        genres: ["Sci-Fi", "Drama"],
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        image: "https://www.hollywoodreporter.com/wp-content/uploads/2014/09/interstellar_poster_0.jpg",
    },
    {
        id: 10,
        title: "John Wick:",
        subtitle: "Chapter 4",
        rating: "7.7",
        duration: "2h 49min",
        genres: ["Action", "Thriller"],
        description: "John Wick uncovers a path to defeating The High Table, but he must face a new enemy with powerful alliances.",
        image: "https://blog.richersounds.com/wp-content/uploads/2023/04/review-john-wick-chapter-4-elevates-the-badass-action-franchise-to-a-new-level.jpg",
    },
    {
        id: 11,
        title: "The Super Mario Bros. Movie",
        subtitle: "The Game is On",
        rating: "7.1",
        duration: "1h 32min",
        genres: ["Animation", "Adventure"],
        description: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
        image: "https://www.syfy.com/sites/syfy/files/2023/02/the_super_mario_bros_movie.jpg",
    },
    {
        id: 12,
        title: "Gladiator II",
        subtitle: "The Saga Continues",
        rating: "7.5",
        duration: "2h 28min",
        genres: ["Action", "Drama"],
        description: "Years after witnessing the death of the revered hero Maximus, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors.",
        image: "https://buckbylibraryhub.org/wp-content/uploads/2025/03/Gladiator-II.jpg",
    },
    {
        id: 13,
        title: "Inception",
        subtitle: "Your Mind is the Scene of the Crime",
        rating: "8.8",
        duration: "2h 28min",
        genres: ["Sci-Fi", "Action"],
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        image: "https://images.bauerhosting.com/legacy/empire-tmdb/films/27205/images/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=undefined&q=80",
    },
    {
        id: 14,
        title: "Inside Out 2",
        subtitle: "Make Room for New Emotions",
        rating: "7.7",
        duration: "1h 36min",
        genres: ["Animation", "Comedy"],
        description: "Joy, Sadness, Anger, Fear and Disgust have been running a successful operation by all accounts. However, when Anxiety shows up, they aren't sure how to feel.",
        image: "https://4kwallpapers.com/images/wallpapers/inside-out-2-movie-2560x1440-16762.jpg",
    },
    {
        id: 15,
        title: "The Dark Knight",
        subtitle: "Welcome to a World Without Rules",
        rating: "9.0",
        duration: "2h 32min",
        genres: ["Action", "Crime"],
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
        image: "https://www.bfoliver.com/images/thedarkknightbanner.jpg",
    },
    {
        id: 16,
        title: "Everything Everywhere",
        subtitle: "All at Once",
        rating: "7.8",
        duration: "2h 19min",
        genres: ["Sci-Fi", "Comedy"],
        description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.",
        image: "https://m.media-amazon.com/images/S/pv-target-images/280624c4631999ef41fb2a63c0f5885d328b0e8da5c181f46c5f26f083c3be9f.jpg",
    },
    {
        id: 17,
        title: "Mad Max:",
        subtitle: "Fury Road",
        rating: "8.1",
        duration: "2h 00min",
        genres: ["Action", "Sci-Fi"],
        description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.",
        image: "https://bloody-disgusting.com/wp-content/uploads/2023/12/furiousa-movie.png",
    },
    {
        id: 18,
        title: "Spirited Away",
        subtitle: "The Masterpiece",
        rating: "8.6",
        duration: "2h 05min",
        genres: ["Animation", "Fantasy"],
        description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
        image: "https://i.ytimg.com/vi/EfYkRhWqX3s/maxresdefault.jpg",
    },
    {
        id: 19,
        title: "Blade Runner 2049",
        subtitle: "There are still pages left to be turned",
        rating: "8.0",
        duration: "2h 44min",
        genres: ["Sci-Fi", "Drama"],
        description: "A young Blade Runner's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
        image: "https://southfloridafilmmaker.com/wp-content/uploads/2017/10/BR2049-WP.jpg",
    },
    {
        id: 20,
        title: "Top Gun:",
        subtitle: "Maverick",
        rating: "8.3",
        duration: "2h 10min",
        genres: ["Action", "Drama"],
        description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past while training a new squad.",
        image: "https://weliveentertainment.com/wp-content/uploads/2022/05/top-gun-banner.jpg",
    },
    {
        id: 21,
        title: "Deadpool & Wolverine",
        subtitle: "The Ultimate Team-Up",
        rating: "8.1",
        duration: "2h 07min",
        genres: ["Action", "Comedy"],
        description: "A weary Wolverine finds himself recovering from his injuries when he crosses paths with the loudmouth Deadpool.",
        image: "https://www.oldtrenchy.com/wp-content/uploads/2024/07/deadpool-and-wolverine-banner.jpg",
    },
    {
        id: 22,
        title: "The Matrix Resurrections",
        subtitle: "Return to the Source",
        rating: "5.7",
        duration: "2h 28min",
        genres: ["Sci-Fi", "Action"],
        description: "Return to a world of two realities: one, everyday life; the other, what lies behind it.",
        image: "https://dccomicsnews.com/wp-content/uploads/2022/03/the-matrix-resurrections-banner.jpg",
    },
    {
        id: 23,
        title: "Puss in Boots:",
        subtitle: "The Last Wish",
        rating: "7.9",
        duration: "1h 42min",
        genres: ["Animation", "Adventure"],
        description: "Puss in Boots discovers that his passion for adventure has taken its toll: he has burned through eight of his nine lives.",
        image: "https://weliveentertainment.com/wp-content/uploads/2022/12/puss-in-boots-banner.jpg",
    },
    {
        id: 24,
        title: "A Quiet Place:",
        subtitle: "Day One",
        rating: "6.7",
        duration: "1h 39min",
        genres: ["Horror", "Sci-Fi"],
        description: "Experience the day the world went silent in this prequel about the initial alien invasion in New York City.",
        image: "https://www.livetts.co.uk/wp-content/uploads/2024/06/a-quiet-place-day-one-poster-landscape.jpg",
    },
    {
        id: 25,
        title: "The Shawshank Redemption",
        subtitle: "Hope is a Good Thing",
        rating: "9.3",
        duration: "2h 22min",
        genres: ["Drama", "Crime"],
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        image: "https://i0.wp.com/justalrightreviews.com/wp-content/uploads/2016/07/the-shawshank-redemption.png?fit=1200%2C675&ssl=1",
    },
    {
        id: 26,
        title: "Moana 2",
        subtitle: "The Ocean is Calling",
        rating: "7.2",
        duration: "1h 40min",
        genres: ["Animation", "Adventure"],
        description: "Moana and Maui reunite for an expansive new voyage alongside a crew of unlikely seafarers.",
        image: "https://images.wallpapersden.com/image/download/moana-2-movie-poster_bWxta2mUmZqaraWkpJRmbmdlrWZlbWU.jpg",
    },
    {
        id: 27,
        title: "The Wolf of Wall Street",
        subtitle: "Earn. Spend. Party.",
        rating: "8.2",
        duration: "3h 00min",
        genres: ["Biography", "Comedy"],
        description: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker to his fall involving crime and corruption.",
        image: "https://images7.alphacoders.com/479/479344.jpg",
    },
    {
        id: 28,
        title: "Parasite",
        subtitle: "Act Like You Own The Place",
        rating: "8.5",
        duration: "2h 12min",
        genres: ["Thriller", "Drama"],
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        image: "https://wallpaperaccess.com/full/2157303.jpg",
    },
    {
        id: 29,
        title: "Kung Fu Panda 4",
        subtitle: "The Dragon Warrior Returns",
        rating: "6.3",
        duration: "1h 34min",
        genres: ["Animation", "Action"],
        description: "After Po is tapped to become the Spiritual Leader of the Valley of Peace, he needs to find and train a new Dragon Warrior.",
        image: "https://images.wallpapersden.com/image/download/kung-fu-panda-4-movie_bWltam2UmZqaraWkpJRmbmdlrWZlbWU.jpg",
    },
    {
        id: 30,
        title: "Titanic",
        subtitle: "Nothing on Earth Could Come Between Them",
        rating: "7.9",
        duration: "3h 14min",
        genres: ["Romance", "Drama"],
        description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        image: "https://images7.alphacoders.com/130/1304561.jpg",
    },
    {
        id: 31,
        title: "The Prestige",
        subtitle: "Are You Watching Closely?",
        rating: "8.5",
        duration: "2h 10min",
        genres: ["Mystery", "Sci-Fi"],
        description: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion.",
        image: "https://images8.alphacoders.com/403/403429.jpg",
    },
    {
        id: 32,
        title: "Kingdom of the Planet of the Apes",
        subtitle: "A New Era Begins",
        rating: "7.0",
        duration: "2h 25min",
        genres: ["Sci-Fi", "Action"],
        description: "Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question everything he's been taught.",
        image: "https://images.wallpapersden.com/image/download/kingdom-of-the-planet-of-the-apes-poster_bWxtam6UmZqaraWkpJRmbmdlrWZlbWU.jpg",
    },
    {
        id: 33,
        title: "The Lion King",
        subtitle: "The King has Returned",
        rating: "8.5",
        duration: "1h 28min",
        genres: ["Animation", "Drama"],
        description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        image: "https://images6.alphacoders.com/102/1023774.jpg",
    },
    {
        id: 34,
        title: "Twisters",
        subtitle: "Fearless. Relentless.",
        rating: "7.1",
        duration: "2h 02min",
        genres: ["Action", "Adventure"],
        description: "An update to the 1996 film 'Twister', which centered on a pair of storm chasers who risk their lives in an attempt to test an experimental weather alert system.",
        image: "https://static1.srcdn.com/wordpress/wp-content/uploads/2024/05/twisters-movie-poster.jpg",
    },
    {
        id: 35,
        title: "Knives Out",
        subtitle: "Everyone has a Motive",
        rating: "7.9",
        duration: "2h 10min",
        genres: ["Mystery", "Comedy"],
        description: "A detective investigates the death of the patriarch of an eccentric, combative family.",
        image: "https://wallpaperaccess.com/full/2085775.jpg",
    },
    {
        id: 36,
        title: "Coco",
        subtitle: "The Celebration of a Lifetime",
        rating: "8.4",
        duration: "1h 45min",
        genres: ["Animation", "Family"],
        description: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.",
        image: "https://images7.alphacoders.com/883/883398.jpg",
    },
    {
        id: 37,
        title: "Alien:",
        subtitle: "Romulus",
        rating: "7.4",
        duration: "1h 59min",
        genres: ["Horror", "Sci-Fi"],
        description: "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
        image: "https://images.wallpapersden.com/image/download/alien-romulus-2024-poster_bWxtaW6UmZqaraWkpJRmbmdlrWZlbWU.jpg",
    },
    {
        id: 38,
        title: "The Green Mile",
        subtitle: "Miracles Happen in Unexpected Places",
        rating: "8.6",
        duration: "3h 09min",
        genres: ["Drama", "Fantasy"],
        description: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments.",
        image: "https://m.media-amazon.com/images/S/pv-target-images/343e06a72e2d0961806307371104e71ce0204736f3223068e83b8b6e68d2777f.jpg",
    },
    {
        id: 39,
        title: "Mission: Impossible:",
        subtitle: "Dead Reckoning",
        rating: "7.7",
        duration: "2h 43min",
        genres: ["Action", "Thriller"],
        description: "Ethan Hunt and his IMF team must track down a dangerous new weapon that threatens all of humanity before it falls into the wrong hands.",
        image: "https://images.wallpapersden.com/image/download/mission-impossible-dead-reckoning-part-one-tom-cruise_bWlpbGWUmZqaraWkpJRmbmdlrWZlbWU.jpg",
    },
    {
        id: 40,
        title: "Your Name",
        subtitle: "I will find you, wherever you are",
        rating: "8.4",
        duration: "1h 46min",
        genres: ["Animation", "Romance"],
        description: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
        image: "https://images7.alphacoders.com/741/741169.jpg",
    },
    {
        id: 41,
        title: "The Godfather",
        subtitle: "An Offer You Can't Refuse",
        rating: "9.2",
        duration: "2h 55min",
        genres: ["Crime", "Drama"],
        description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        image: "https://images8.alphacoders.com/133/1331776.jpg",
    },
    {
        id: 42,
        title: "Gladiator",
        subtitle: "What We Do In Life Echoes In Eternity",
        rating: "8.5",
        duration: "2h 35min",
        genres: ["Action", "Drama"],
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        image: "https://images.alphacoders.com/437/437936.jpg",
    },
    {
        id: 43,
        title: "Toy Story 4",
        subtitle: "On the Road to Adventure",
        rating: "7.7",
        duration: "1h 40min",
        genres: ["Animation", "Comedy"],
        description: "When a new toy called 'Forky' joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
        image: "https://images8.alphacoders.com/101/1013715.jpg",
    },
    {
        id: 44,
        title: "Pulp Fiction",
        subtitle: "You Won't Know the Facts Until You've Seen the Fiction",
        rating: "8.9",
        duration: "2h 34min",
        genres: ["Crime", "Drama"],
        description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        image: "https://images7.alphacoders.com/494/494191.jpg",
    },
    {
        id: 45,
        title: "Shrek",
        subtitle: "The Greatest Fairy Tale Never Told",
        rating: "7.9",
        duration: "1h 30min",
        genres: ["Animation", "Comedy"],
        description: "A mean-spirited ogre manages to rescue a princess who had been cursed to be a monster by night, only to fall in love with her.",
        image: "https://images.alphacoders.com/219/219196.jpg",
    },
    {
        id: 46,
        title: "Inception:",
        subtitle: "The Dream is Real",
        rating: "8.8",
        duration: "2h 28min",
        genres: ["Action", "Adventure"],
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        image: "https://images.alphacoders.com/147/147431.jpg",
    },
    {
        id: 47,
        title: "Whiplash",
        subtitle: "Not Quite My Tempo",
        rating: "8.5",
        duration: "1h 46min",
        genres: ["Drama", "Music"],
        description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.",
        image: "https://m.media-amazon.com/images/S/pv-target-images/611a91e56993c13867f1b142f1f0093a027376c99c8942b109f5835695029329.jpg",
    },
    {
        id: 48,
        title: "Finding Nemo",
        subtitle: "There are more than 3.7 trillion fish in the ocean. They're looking for one.",
        rating: "8.2",
        duration: "1h 40min",
        genres: ["Animation", "Adventure"],
        description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        image: "https://images6.alphacoders.com/308/308945.jpg",
    },
    {
        id: 49,
        title: "Joker",
        subtitle: "Put On A Happy Face",
        rating: "8.4",
        duration: "2h 02min",
        genres: ["Crime", "Drama"],
        description: "A mentally troubled comedian is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
        image: "https://images.alphacoders.com/102/1027154.jpg",
    },
    {
        id: 50,
        title: "How to Train Your Dragon",
        subtitle: "One Friendship Will Change Two Worlds",
        rating: "8.1",
        duration: "1h 38min",
        genres: ["Animation", "Action"],
        description: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself.",
        image: "https://images7.alphacoders.com/112/1128509.jpg",
    },
];

export const TopTrending = MOVIES;